官網的範例

In [5]:
# 導入 yfinance 庫
import yfinance as yf  
# 建立一個 Ticker 物件代表微軟公司 (股票代碼：MSFT)
msft = yf.Ticker("MSFT")  

# 獲取所有股票信息
# 獲取微軟公司的所有股票信息
msft.info  

# 獲取歷史市場數據
# 獲取微軟公司過去一個月的歷史市場數據
hist = msft.history(period="1mo")  

# 顯示關於歷史數據的元信息（需要先調用 history() 方法）
# 顯示歷史數據的元信息
msft.history_metadata  

# 顯示行動（股息、分股、資本收益）
# 顯示微軟公司的所有行動（包括股息和分股）
msft.actions  
# 顯示微軟公司的股息
msft.dividends  
# 顯示微軟公司的分股
msft.splits  
# 顯示資本收益（僅限於共同基金和 ETFs）
msft.capital_gains  

# 顯示股票數量
# 從 2022 年 1 月 1 日開始的股票數量
msft.get_shares_full(start="2022-01-01", end=None)  

# 顯示財務報表：
# - 收益表
# 年度收益表
msft.income_stmt  
# 季度收益表
msft.quarterly_income_stmt  
# - 資產負債表
# 年度資產負債表
msft.balance_sheet  
# 季度資產負債表
msft.quarterly_balance_sheet  
# - 現金流量表
# 年度現金流量表
msft.cashflow  
# 季度現金流量表
msft.quarterly_cashflow  
# 更多選項見 `Ticker.get_income_stmt()`

# 顯示持有者
# 主要持有者
msft.major_holders  
# 機構持有者
msft.institutional_holders  
# 共同基金持有者
msft.mutualfund_holders  

# 顯示未來和歷史盈利日期，預設最多顯示接下來 4 個季度和最近 8 個季度的數據。
# 注意：如果需要更多數據，使用 msft.get_earnings_dates(limit=XX) 並增加 limit 參數。
msft.earnings_dates

# 顯示 ISIN 代碼 - *實驗性功能*
# ISIN = 國際證券識別碼
print(msft.isin)

# 顯示期權到期日
# 顯示微軟公司的期權到期日
print(msft.options)

# 顯示新聞
# 顯示有關微軟公司的最新新聞
print(msft.news)

# 獲取特定到期日的期權鏈
# 將 'YYYY-MM-DD' 替換為 '2023-12-15'
opt = msft.option_chain('2023-12-15')  
# 數據可通過：opt.calls, opt.puts 獲取
opt

-
('2023-12-15', '2023-12-22', '2023-12-29', '2024-01-05', '2024-01-12', '2024-01-19', '2024-01-26', '2024-02-16', '2024-03-15', '2024-04-19', '2024-05-17', '2024-06-21', '2024-07-19', '2024-09-20', '2024-12-20', '2025-01-17', '2025-06-20', '2025-12-19', '2026-01-16')
[{'uuid': '498cc109-3948-30ca-b07c-d8f071a69e69', 'title': 'Dow Jones Futures Rise With Fed Rate Shift Seen; Tesla Model 3 Variants To Lose $7,500 Tax Credit', 'publisher': "Investor's Business Daily", 'link': 'https://finance.yahoo.com/m/498cc109-3948-30ca-b07c-d8f071a69e69/dow-jones-futures-rise-with.html', 'providerPublishTime': 1702461330, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/z3r9pB4r2orevANbsCV0Aw--~B/aD02MDA7dz0xMDY1O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/5f0ef20dfa643b73d5c95a986dfd5ee0', 'width': 1065, 'height': 600, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/XjS01JP5A5SIlxE2.s9YqQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/5f0ef20dfa643b73d5c95a986dfd5ee0', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['NVDA', '^DJI', '^GSPC', 'COMP', 'TSLA', 'MSFT', 'DDOG', 'FRSH', 'AMZN', 'NFLX', '^VIX']}, {'uuid': 'a825bc35-e496-357a-9dc1-9e5ffdd0c4c6', 'title': 'PRESS DIGEST- New York Times business news - Dec 13', 'publisher': 'Reuters', 'link': 'https://finance.yahoo.com/news/press-digest-york-times-business-055747392.html', 'providerPublishTime': 1702447067, 'type': 'STORY', 'relatedTickers': ['MSFT']}, {'uuid': 'fa0b5c01-ae38-3839-b0ce-b34f23762925', 'title': 'Johnson Controls, Zillow Group, Oracle: Trending tickers', 'publisher': 'Yahoo Finance Video', 'link': 'https://finance.yahoo.com/video/johnson-controls-zillow-group-oracle-221428436.html', 'providerPublishTime': 1702419268, 'type': 'VIDEO', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gd.uzU4.DbNbKeVfZaWw1w--~B/aD0xNTk1O3c9MjgzOTthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-12/e078de60-9938-11ee-aef5-dad40b50f964', 'width': 2839, 'height': 1595, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/1NVyTR0SOwbenYwzK4F_aA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2023-12/e078de60-9938-11ee-aef5-dad40b50f964', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['AMZN', 'MSFT', 'JCI', 'ORCL', 'Z', 'ZG']}, {'uuid': '53bdadb7-6125-357b-895e-7fa137587302', 'title': 'Indexes Gain Momentum Amid Inflation News; Cathie Wood Buys More Microsoft, Meta', 'publisher': "Investor's Business Daily", 'link': 'https://finance.yahoo.com/m/53bdadb7-6125-357b-895e-7fa137587302/indexes-gain-momentum-amid.html', 'providerPublishTime': 1702413081, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/yFYixt4zfmpEGBBg4OOySw--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/c17b5b65818a93054b26ab66c9c27269', 'width': 1000, 'height': 563, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/1T1bZIustlZy3R5TX9lYzg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/c17b5b65818a93054b26ab66c9c27269', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['MSFT', 'META', 'HAS', 'BKNG']}, {'uuid': 'df74c47d-1a41-310f-921b-2c2829adc777', 'title': 'This Former PlayStation Executive Says Japanese Video Games Need Xbox to Grow', 'publisher': 'Bloomberg', 'link': 'https://finance.yahoo.com/news/playstation-veteran-helping-xbox-relevant-203000964.html', 'providerPublishTime': 1702413000, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ZeG3ZYnolGn0cUWvpsGMEQ--~B/aD0xMzMzO3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/bloomberg_technology_68/1309a43603ee6154884d995597b33693', 'width': 2000, 'height': 1333, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/MSdDvgI__Fwr7rmIKpbCWQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_technology_68/1309a43603ee6154884d995597b33693', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['MSFT', 'NTDOY']}, {'uuid': '65b53896-faf4-3a06-9d0d-a63cf3c83192', 'title': 'Best Dow Jones Stocks To Buy And Watch In December 2023: Apple At Buy Point', 'publisher': "Investor's Business Daily", 'link': 'https://finance.yahoo.com/m/65b53896-faf4-3a06-9d0d-a63cf3c83192/best-dow-jones-stocks-to-buy.html', 'providerPublishTime': 1702407513, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/JPX5jeyihDRi4N6ueuYJVQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/ed4e9880b0c3e9257977ca3554a6c383', 'width': 1000, 'height': 563, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/.0m6SEAzHJOxc1V1Vw8fuA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/ed4e9880b0c3e9257977ca3554a6c383', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['^DJI', 'MSFT', 'AAPL']}, {'uuid': '72dfff6e-510d-30db-95d3-66089fd7faf3', 'title': '10 A-Rated Stocks Billionaires Are Loading Up On', 'publisher': 'Insider Monkey', 'link': 'https://finance.yahoo.com/news/10-rated-stocks-billionaires-loading-162227528.html', 'providerPublishTime': 1702398147, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/5i30it7RT8AZBHZBJSSzig--~B/aD0xNDQwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/insidermonkey.com/af2bb6bdbc4f56cfaf197a2118a94cf1', 'width': 1920, 'height': 1440, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/b2WIEOGrTq3818NJRrJ71Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/af2bb6bdbc4f56cfaf197a2118a94cf1', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['COMP', '^GSPC', 'JNJ', 'CVX', 'CSCO', 'TSM', 'MSFT', 'AAPL', 'AMZN', 'GOOG']}, {'uuid': '3f3e92f9-8907-3721-8970-92673d506e6a', 'title': 'Insider Sell: EVP, Chief Human Resources Officer Kathleen Hogan Sells 24,681 Shares of ...', 'publisher': 'GuruFocus.com', 'link': 'https://finance.yahoo.com/news/insider-sell-evp-chief-human-160600558.html', 'providerPublishTime': 1702397160, 'type': 'STORY', 'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/tJD_Q8noHpvso1HuQczmMw--~B/aD00MDA7dz00MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/us.finance.gurufocus/656a936f73bd055ea8cb9ae0fcc7966c', 'width': 400, 'height': 400, 'tag': 'original'}, {'url': 'https://s.yimg.com/uu/api/res/1.2/MrG_I2WdpkC50NbKW8xTbw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/us.finance.gurufocus/656a936f73bd055ea8cb9ae0fcc7966c', 'width': 140, 'height': 140, 'tag': '140x140'}]}, 'relatedTickers': ['MSFT']}]

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice  bid  \
0   MSFT231215C00160000 2023-12-12 20:54:50+00:00   160.0     213.35  0.0
1   MSFT231215C00165000 2023-12-12 14:32:13+00:00   165.0     206.10  0.0
2   MSFT231215C00170000 2023-12-12 14:32:15+00:00   170.0     201.00  0.0
3   MSFT231215C00175000 2023-12-08 20:45:14+00:00   175.0     198.33  0.0
4   MSFT231215C00180000 2023-11-24 15:40:48+00:00   180.0     196.93  0.0
..                  ...                       ...     ...        ...  ...
85  MSFT231215C00520000 2023-11-20 19:47:00+00:00   520.0       0.01  0.0
86  MSFT231215C00525000 2023-11-10 17:53:39+00:00   525.0       0.02  0.0
87  MSFT231215C00530000 2023-11-14 15:28:57+00:00   530.0       0.01  0.0
88  MSFT231215C00535000 2023-10-20 13:40:02+00:00   535.0       0.02  0.0
89  MSFT231215C00540000 2023-12-11 14:30:12+00:00   540.0       0.01  0.0

     ask  change  percentChange  volume  openInterest  impliedVolatility  \
0   0.00     0.0            0.0       4             0           0.000010
1   0.00     0.0            0.0       1             0           0.000010
2   0.00     0.0            0.0       5             0           0.000010
3   0.00     0.0            0.0      10             0           0.000010
4   0.00     0.0            0.0       3             0           0.000010
..   ...     ...            ...     ...           ...                ...
85  0.00     0.0            0.0     234             0           0.500005
86  0.21     0.0            0.0      68           301           1.468753
87  0.00     0.0            0.0     156             0           0.500005
88  2.13     0.0            0.0     110           129           2.122563
89  0.00     0.0            0.0       1             0           0.500005

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
..         ...          ...      ...
85       False      REGULAR      USD
86       False      REGULAR      USD
87       False      REGULAR      USD
88       False      REGULAR      USD
89       False      REGULAR      USD

[90 rows x 14 columns], puts=         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   MSFT231215P00160000 2023-11-20 14:38:26+00:00   160.0       0.01    0.00
1   MSFT231215P00165000 2023-11-10 15:08:56+00:00   165.0       0.01    0.00
2   MSFT231215P00170000 2023-11-17 18:26:26+00:00   170.0       0.01    0.00
3   MSFT231215P00175000 2023-12-08 17:52:26+00:00   175.0       0.01    0.00
4   MSFT231215P00180000 2023-12-08 17:50:05+00:00   180.0       0.01    0.00
..                  ...                       ...     ...        ...     ...
84  MSFT231215P00520000 2023-09-26 13:39:58+00:00   520.0     204.38  190.05
85  MSFT231215P00525000 2023-08-31 19:57:13+00:00   525.0     196.96  207.10
86  MSFT231215P00530000 2023-12-11 20:51:29+00:00   530.0     159.55    0.00
87  MSFT231215P00535000 2023-12-11 20:51:29+00:00   535.0     164.55    0.00
88  MSFT231215P00540000 2023-12-12 20:55:08+00:00   540.0     166.35    0.00

       ask  change  percentChange  volume  openInterest  impliedVolatility  \
0     0.00     0.0            0.0      10             0           0.500005
1     0.22     0.0            0.0       3           161           3.464845
2     0.00     0.0            0.0       1             0           0.500005
3     0.00     0.0            0.0      34             0           0.500005
4     0.00     0.0            0.0     174             0           0.500005
..     ...     ...            ...     ...           ...                ...
84  193.25     0.0            0.0       4             0           6.509767
85  210.40     0.0            0.0       4             0           7.498658
86    0.00     0.0            0.0       1             0           0.000010
87    0.00     0.0            0.0       3             0           0.000010
88    0.00     0.0            0.0       4             0           0.000010

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
..         ...          ...      ...
84        True      REGULAR      USD
85        True      REGULAR      USD
86        True      REGULAR      USD
87        True      REGULAR      USD
88        True      REGULAR      USD

[89 rows x 14 columns], underlying={'language': 'en-US', 'region': 'US', 'quoteType': 'EQUITY', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'currency': 'USD', 'marketState': 'PRE', 'regularMarketChangePercent': 0.8295225, 'regularMarketPrice': 374.38, 'exchange': 'NMS', 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'messageBoardId': 'finmb_21835', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'gmtOffSetMilliseconds': -18000000, 'market': 'us_market', 'esgPopulated': False, 'firstTradeDateMilliseconds': 511108200000, 'priceHint': 2, 'preMarketChange': 0.7200012, 'preMarketChangePercent': 0.19231829, 'preMarketTime': 1702461637, 'preMarketPrice': 375.1, 'regularMarketChange': 3.080017, 'regularMarketTime': 1702414801, 'regularMarketDayHigh': 374.42, 'regularMarketDayRange': '370.46 - 374.42', 'regularMarketDayLow': 370.46, 'regularMarketVolume': 24493072, 'regularMarketPreviousClose': 371.3, 'bid': 0.0, 'ask': 0.0, 'bidSize': 8, 'askSize': 11, 'fullExchangeName': 'NasdaqGS', 'financialCurrency': 'USD', 'regularMarketOpen': 370.85, 'averageDailyVolume3Month': 25195904, 'averageDailyVolume10Day': 26027420, 'fiftyTwoWeekLowChange': 155.03, 'fiftyTwoWeekLowChangePercent': 0.70677, 'fiftyTwoWeekRange': '219.35 - 384.3', 'fiftyTwoWeekHighChange': -9.919983, 'fiftyTwoWeekHighChangePercent': -0.025813123, 'fiftyTwoWeekLow': 219.35, 'fiftyTwoWeekHigh': 384.3, 'fiftyTwoWeekChangePercent': 44.351135, 'dividendDate': 1710374400, 'earningsTimestamp': 1698183000, 'earningsTimestampStart': 1705921140, 'earningsTimestampEnd': 1706270400, 'trailingAnnualDividendRate': 2.79, 'trailingPE': 36.242016, 'dividendRate': 3.0, 'trailingAnnualDividendYield': 0.0075141396, 'dividendYield': 0.8, 'epsTrailingTwelveMonths': 10.33, 'epsForward': 12.96, 'epsCurrentYear': 11.24, 'priceEpsCurrentYear': 33.30783, 'sharesOutstanding': 7432260096, 'bookValue': 29.702, 'fiftyDayAverage': 351.4698, 'fiftyDayAverageChange': 22.910217, 'fiftyDayAverageChangePercent': 0.06518403, 'twoHundredDayAverage': 322.28674, 'twoHundredDayAverageChange': 52.09326, 'twoHundredDayAverageChangePercent': 0.16163638, 'marketCap': 2782489477120, 'forwardPE': 28.887346, 'priceToBook': 12.604539, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.7 - Buy', 'tradeable': False, 'cryptoTradeable': False, 'displayName': 'Microsoft', 'symbol': 'MSFT'})

如果您想使用代理伺服器下載數據

In [6]:
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')

# access each ticker using (example)
tickers.tickers['MSFT'].info
tickers.tickers['AAPL'].history(period="1mo")
tickers.tickers['GOOG'].actions

                           Dividends  Stock Splits
Date
2014-03-27 00:00:00-04:00        0.0      2.002000
2015-04-27 00:00:00-04:00        0.0      1.002746
2022-07-18 00:00:00-04:00        0.0     20.000000

要將價格歷史記錄下載到一張表中

In [7]:
import yfinance as yf
data = yf.download("SPY AAPL", period="1mo")
data

[*********************100%%**********************]  2 of 2 completed

             Adj Close                   Close                    High  \
                  AAPL         SPY        AAPL         SPY        AAPL
Date
2023-11-13  184.800003  440.190002  184.800003  440.190002  186.029999
2023-11-14  187.440002  448.730011  187.440002  448.730011  188.110001
2023-11-15  188.009995  449.679993  188.009995  449.679993  189.500000
2023-11-16  189.710007  450.230011  189.710007  450.230011  190.960007
2023-11-17  189.690002  450.790009  189.690002  450.790009  190.380005
2023-11-20  191.449997  454.260010  191.449997  454.260010  191.910004
2023-11-21  190.639999  453.269989  190.639999  453.269989  191.520004
2023-11-22  191.309998  455.019989  191.309998  455.019989  192.929993
2023-11-24  189.970001  455.299988  189.970001  455.299988  190.899994
2023-11-27  189.789993  454.480011  189.789993  454.480011  190.669998
2023-11-28  190.399994  454.929993  190.399994  454.929993  191.080002
2023-11-29  189.369995  454.609985  189.369995  454.609985  192.089996
2023-11-30  189.949997  456.399994  189.949997  456.399994  190.320007
2023-12-01  191.240005  459.100006  191.240005  459.100006  191.559998
2023-12-04  189.429993  456.690002  189.429993  456.690002  190.050003
2023-12-05  193.419998  456.600006  193.419998  456.600006  194.399994
2023-12-06  192.320007  454.760010  192.320007  454.760010  194.759995
2023-12-07  194.270004  458.230011  194.270004  458.230011  195.000000
2023-12-08  195.710007  460.200012  195.710007  460.200012  195.990005
2023-12-11  193.179993  461.989990  193.179993  461.989990  193.490005
2023-12-12  194.710007  464.100006  194.710007  464.100006  194.720001

                               Low                    Open              \
                   SPY        AAPL         SPY        AAPL         SPY
Date
2023-11-13  441.329987  184.210007  438.420013  185.820007  439.230011
2023-11-14  450.059998  186.300003  446.089996  187.699997  446.320007
2023-11-15  451.380005  187.779999  448.799988  187.850006  450.109985
2023-11-16  450.559998  188.649994  448.119995  189.570007  449.220001
2023-11-17  451.420013  188.570007  449.290009  190.250000  450.239990
2023-11-20  455.130005  189.880005  450.519989  189.889999  450.529999
2023-11-21  454.130005  189.740005  451.959991  191.410004  453.179993
2023-11-22  456.380005  190.830002  453.890015  191.490005  454.980011
2023-11-24  455.500000  189.250000  454.730011  190.869995  455.070007
2023-11-27  455.489990  188.899994  454.079987  189.919998  454.649994
2023-11-28  456.269989  189.399994  453.500000  189.779999  454.079987
2023-11-29  458.320007  188.970001  454.200012  190.899994  457.149994
2023-11-30  456.760010  188.190002  453.339996  189.839996  455.480011
2023-12-01  459.649994  189.229996  455.160004  190.330002  455.769989
2023-12-04  459.119995  187.449997  454.339996  189.979996  455.600006
2023-12-05  457.589996  190.179993  454.869995  190.210007  455.260010
2023-12-06  458.839996  192.110001  454.309998  194.449997  458.809998
2023-12-07  458.899994  193.589996  456.290009  193.630005  456.910004
2023-12-08  460.750000  193.669998  457.209991  194.199997  457.459991
2023-12-11  462.170013  191.419998  459.470001  193.110001  459.690002
2023-12-12  464.200012  191.720001  460.600006  193.080002  461.630005

              Volume
                AAPL       SPY
Date
2023-11-13  43627500  52236100
2023-11-14  60108400  97176900
2023-11-15  53790500  77327600
2023-11-16  54412900  66665800
2023-11-17  50922700  83133200
2023-11-20  46505100  69936200
2023-11-21  38134500  49244600
2023-11-22  39617700  59394900
2023-11-24  24048300  29737400
2023-11-27  40552600  50506000
2023-11-28  38415400  62115000
2023-11-29  43014200  63146000
2023-11-30  48794400  79752700
2023-12-01  45679300  89097900
2023-12-04  43389500  72430900
2023-12-05  66628400  69793500
2023-12-06  41089700  69124700
2023-12-07  47477700  66995400
2023-12-08  53377300  83080900
2023-12-11  60943700  65002200
2023-12-12  52660600  67908700

若要自訂請求，將 session= 參數傳遞給 Ticker 建構函數。

In [9]:
%pip install requests_cache

Collecting requests_cache
  Using cached requests_cache-1.1.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: attrs>=21.2 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests_cache) (23.1.0)
Collecting cattrs>=22.2 (from requests_cache)
  Using cached cattrs-23.2.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.5 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests_cache) (4.1.0)
Requirement already satisfied: requests>=2.22 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests_cache) (2.31.0)
Collecting url-normalize>=1.4 (from requests_cache)
  Using cached url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: urllib3>=1.25.5 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests_cache) (2.1.0)
Requirement already satisfied: exceptiongroup>=1.1.1 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from cattrs>=22.2->requests_cache) (1.2.0)
Requirement already satisfied: typing-extensions!=4.6.3,>=4.1.0 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from cattrs>=22.2->requests_cache) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.22->requests_cache) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.22->requests_cache) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.22->requests_cache) (2023.11.17)
Requirement already satisfied: six in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from url-normalize>=1.4->requests_cache) (1.16.0)
Using cached requests_cache-1.1.1-py3-none-any.whl (60 kB)
Using cached cattrs-23.2.3-py3-none-any.whl (57 kB)
Installing collected packages: url-normalize, cattrs, requests_cache
Successfully installed cattrs-23.2.3 requests_cache-1.1.1 url-normalize-1.4.3
Note: you may need to restart the kernel to use updated packages.

In [10]:
import requests_cache
session = requests_cache.CachedSession('yfinance.cache')
session.headers['User-agent'] = 'my-program/1.0'
ticker = yf.Ticker('msft', session=session)
# The scraped response will be stored in the cache
ticker.actions

                           Dividends  Stock Splits
Date
1987-09-21 00:00:00-04:00       0.00           2.0
1990-04-16 00:00:00-04:00       0.00           2.0
1991-06-27 00:00:00-04:00       0.00           1.5
1992-06-15 00:00:00-04:00       0.00           1.5
1994-05-23 00:00:00-04:00       0.00           2.0
...                              ...           ...
2022-11-16 00:00:00-05:00       0.68           0.0
2023-02-15 00:00:00-05:00       0.68           0.0
2023-05-17 00:00:00-04:00       0.68           0.0
2023-08-16 00:00:00-04:00       0.68           0.0
2023-11-15 00:00:00-05:00       0.75           0.0

[89 rows x 2 columns]

將 requests_cache 與速率限制相結合，以避免觸發雅虎的速率限制器/阻止程序，從而損壞資料。

In [12]:
%pip install requests_ratelimiter

Collecting requests_ratelimiter
  Using cached requests_ratelimiter-0.4.2-py3-none-any.whl.metadata (11 kB)
Collecting pyrate-limiter<3.0,>=2.8 (from requests_ratelimiter)
  Using cached pyrate_limiter-2.10.0-py3-none-any.whl (16 kB)
Requirement already satisfied: requests>=2.20 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests_ratelimiter) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.20->requests_ratelimiter) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.20->requests_ratelimiter) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.20->requests_ratelimiter) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/samhsiao/Documents/PythonVenv/envDash/lib/python3.10/site-packages (from requests>=2.20->requests_ratelimiter) (2023.11.17)
Using cached requests_ratelimiter-0.4.2-py3-none-any.whl (8.6 kB)
Installing collected packages: pyrate-limiter, requests_ratelimiter
Successfully installed pyrate-limiter-2.10.0 requests_ratelimiter-0.4.2
Note: you may need to restart the kernel to use updated packages.

In [13]:
from requests import Session
from requests_cache import CacheMixin, SQLiteCache
from requests_ratelimiter import LimiterMixin, MemoryQueueBucket
from pyrate_limiter import Duration, RequestRate, Limiter
class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    pass

session = CachedLimiterSession(
    limiter=Limiter(RequestRate(2, Duration.SECOND*5)),  # max 2 requests per 5 seconds
    bucket_class=MemoryQueueBucket,
    backend=SQLiteCache("yfinance.cache"),
)

In [14]:
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")
data

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-01-03,225.039993,225.830002,223.880005,225.240005,200.629700,91366500
2017-01-04,225.619995,226.750000,225.610001,226.580002,201.823242,78744400
2017-01-05,226.270004,226.580002,225.479996,226.399994,201.662949,78379000
2017-01-06,226.529999,227.750000,225.899994,227.210007,202.384430,71559900
2017-01-09,226.910004,227.070007,226.419998,226.460007,201.716339,46939700
...,...,...,...,...,...,...
2017-04-24,237.179993,237.410004,234.559998,237.169998,212.175247,119209900
2017-04-25,237.910004,238.949997,237.809998,238.550003,213.409805,76698300
2017-04-26,238.509995,239.529999,238.350006,238.399994,213.275620,84702500
2017-04-27,238.770004,238.949997,237.979996,238.600006,213.454529,57410300
2017-04-28,238.899994,238.929993,237.929993,238.080002,212.989365,63532800